FROM ubuntu:20.04

ARG HUGO_VERSION=0.88.1

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt install --yes \
    git \
    node-autoprefixer \
    node-postcss \
    npm \
    sudo \
    wget

WORKDIR /tmp
RUN wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
RUN tar xvf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
RUN mv hugo /usr/bin/
RUN mkdir /site

# RUN npm install --global autoprefixer
# RUN npm install --global postcss-cli

RUN echo "root:ubuntu" | chpasswd

ENV HUGO_ENV production
WORKDIR /site
CMD ["/usr/bin/hugo", "serve", "--bind", "0.0.0.0", "--disableFastRender"]

# Local Variables:
# mode: dockerfile
# End:
