FROM jekyll/builder:latest

RUN apt-get update
RUN DPKG_FRONTEND=noninteractive apt-get upgrade --yes

RUN useradd --create-home docs
USER docs

ENV GEM_HOME=/home/docs/gems
ENV GEM_PATH=/home/docs/gems
ENV PATH=/home/docs/gems/bin:${PATH}

COPY docs/Gemfile /home/docs

WORKDIR /home/docs
RUN gem install jekyll bundler
RUN bundle install
RUN bundle info minima

WORKDIR /docs

EXPOSE 4000
CMD /home/docs/gems/bin/jekyll serve \
    -d /docs/_site --watch --force_polling -H 0.0.0.0 -P 4000

# Local Variables:
# mode: dockerfile
# End:
